changes as suggested !

diff --git a/src/dotnet/.devcontainer/Dockerfile b/src/dotnet/.devcontainer/Dockerfile
--- a/src/dotnet/.devcontainer/Dockerfile
+++ b/src/dotnet/.devcontainer/Dockerfile
@@ -10,20 +10,9 @@ RUN if [ "${VARIANT#*noble}" != "$VARIANT" ]; then \
         # Check if ubuntu user exists and delete it if it does
         if id "ubuntu" &>/dev/null; then \
             echo "Deleting user ubuntu" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \
+            echo "Deleting group associated with ubuntu" && groupdel ubuntu || echo "Failed to delete group associated with ubuntu user"; \
         else \
             echo "User ubuntu does not exist"; \
-        fi; \
-        # Ensure UID 1000 is not in use by another user
-        if id -u 1000 &>/dev/null; then \
-            echo "UID 1000 is already taken by another user. Exiting."; \
-        else \
-            # Check if vscode user exists, if not create it
-            if ! id "vscode" &>/dev/null; then \
-                echo "Creating user vscode" && useradd -m vscode || echo "Failed to create vscode user"; \
-            fi; \
-            # Modify vscode user and group only if they exist
-            echo "Modifying user vscode UID" && usermod -u 1000 vscode || echo "Failed to modify vscode UID"; \
-            echo "Modifying group vscode GID" && groupmod -g 1000 vscode || echo "Failed to modify vscode GID"; \
         fi; \
     else \
         echo "Variant does not contain noble"; \
