few changes for testing ..

diff --git a/src/base-ubuntu/.devcontainer/Dockerfile b/src/base-ubuntu/.devcontainer/Dockerfile
--- a/src/base-ubuntu/.devcontainer/Dockerfile
+++ b/src/base-ubuntu/.devcontainer/Dockerfile
@@ -1,4 +1,5 @@
 ARG VARIANT="noble"
+# ARG VARIANT="8.0-bookworm-slim"
 FROM buildpack-deps:${VARIANT}-curl
 
 LABEL dev.containers.features="common"
@@ -12,6 +13,9 @@ RUN if [ "$VARIANT" = "noble" ]; then \
         if id "ubuntu" &>/dev/null; then \
             echo "Deleting user ubuntu" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \
             echo "Deleting group associated with ubuntu" && groupdel ubuntu || echo "Failed to delete group associated with ubuntu user"; \
+            #check if group 1000 and user 1000 is deleted
+            echo "Checking user at 1000 uid" && getent passwd 1000; || echo "Failed to find user at uid 1000" \
+            echo "Checking group at 1000 gid" &&  getent group 1000; || echo "Failed to find group at gid 1000" \
         else \
             echo "User ubuntu does not exist"; \
         fi; \
