Update Dockerfile to handle 'resolute' variant in user deletion logic

diff --git a/src/base-ubuntu/.devcontainer/Dockerfile b/src/base-ubuntu/.devcontainer/Dockerfile
--- a/src/base-ubuntu/.devcontainer/Dockerfile
+++ b/src/base-ubuntu/.devcontainer/Dockerfile
@@ -4,12 +4,12 @@ FROM buildpack-deps:${VARIANT}-curl
 LABEL dev.containers.features="common"
 
 ARG VARIANT
-RUN if [ "$VARIANT" = "noble" ]; then \
-        if id "ubuntu" &>/dev/null; then \
-            echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
-        else \
-            echo "User 'ubuntu' does not exist for $VARIANT"; \ 
-        fi; \
+RUN if [ "$VARIANT" = "noble" ] || [ "$VARIANT" = "resolute" ]; then \
+    if id "ubuntu" &>/dev/null; then \
+    echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
+    else \
+    echo "User 'ubuntu' does not exist for $VARIANT"; \ 
+    fi; \
     fi
 
 # [Optional] Uncomment this section to install additional OS packages.
