Enhance user deletion logic and add support for 'resolute' variant in user checks

diff --git a/src/base-ubuntu/.devcontainer/Dockerfile b/src/base-ubuntu/.devcontainer/Dockerfile
--- a/src/base-ubuntu/.devcontainer/Dockerfile
+++ b/src/base-ubuntu/.devcontainer/Dockerfile
@@ -6,9 +6,9 @@ LABEL dev.containers.features="common"
 ARG VARIANT
 RUN if [ "$VARIANT" = "noble" ] || [ "$VARIANT" = "resolute" ]; then \
     if id "ubuntu" &>/dev/null; then \
-    echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
+        echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \
     else \
-    echo "User 'ubuntu' does not exist for $VARIANT"; \ 
+        echo "User 'ubuntu' does not exist for $VARIANT"; \
     fi; \
     fi
 
