[base-ubuntu] - remove existing ubuntu user (#1170)
* [base-ubuntu, dotnet] - del existing ubuntu user

* few changes

* few more changes miscellaneous

* misc. changes

* changes to kill process running on 1000 before assigning to vscode user

* more change to assign 1000 to vscode

* small change

* changes as suggested !

* few changes for testing ..

* small change

* few changes..

* reverting dotnet changes..

* changes as suggested

* chg

* Update test.sh

* changed test - check for ubuntu user after deletion added

* changes as discussed in review comment

* changes as required

* changes suggested

diff --git a/src/base-ubuntu/.devcontainer/Dockerfile b/src/base-ubuntu/.devcontainer/Dockerfile
--- a/src/base-ubuntu/.devcontainer/Dockerfile
+++ b/src/base-ubuntu/.devcontainer/Dockerfile
@@ -3,6 +3,15 @@ FROM buildpack-deps:${VARIANT}-curl
 
 LABEL dev.containers.features="common"
 
+ARG VARIANT
+RUN if [ "$VARIANT" = "noble" ]; then \
+        if id "ubuntu" &>/dev/null; then \
+            echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
+        else \
+            echo "User 'ubuntu' does not exist for $VARIANT"; \ 
+        fi; \
+    fi
+
 # [Optional] Uncomment this section to install additional OS packages.
 # RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
 #     && apt-get -y install --no-install-recommends <your-package-list-here>
